### PR TITLE
Recording in Stage Channels

### PR DESCRIPTION
**Pull request by gru2007**
### Changes

- [x] Internal code

Closes Issue: NaN

## Description

Adds a few checks to be able to record in stage channels. This is small change, but mettings recording is an interesting feature. Our administration is crazy about that feature.

### CODE REVIEW

**Comment by DxsSucuk** [comment]
Thanks for the PR!
I sadly dont have any access to a PC rn to test these changes and to review them. Once I do, I will be reviewing it and merge it.

**Comment by gru2007** [comment]
No problem, thanks

**Comment by DxsSucuk** [comment]
I will be closing this PR, but I have added the requested functionality while also keeping all the message stuff intakt: https://github.com/Ree6-Applications/Ree6/commit/62cdc5903e564884ceffe17500d9651e4aabee6f

**Comment by gru2007** [comment]
@DxsSucuk Great, thank you. 
I’ll update my fork to your code, you are coding better than me)

**Pull request closed without merging**
